### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by Lumphie** [Lumphie/CourseCPP#3]
Travis is giving tons of errors @richelbilderbeek 

Only OCLint errors I see are in the random.h and utils.h from Sander.

**Comment by Lumphie** [comment]
Okay now it works.

Only OCLint errors I can't remove are Sander's and 2 parameter reassignments I don't want to remove (because I put them there on purpose)

**Comment by Lumphie** [comment]
Oh and I did find one bug:

removeSubunit(event, .....) 

should be removeSubunit(event - nTotal, ....)

Because otherwise it will look at filaments 13-25 that do not exist.

**Comment by richelbilderbeek** [comment]
I hope you agree that, as this is part of a course, I will not fix your problem, but give some advice instead.

My prime suggestions would be:
- create tests, with simple cases that prove that your functions work as intented
- remove the global variables

Some minor suggestions:
- simpify main, e.g. by creating a function called 'createInitialFilaments' 
- the OCLint complaint about parameter reassignment is a rather valid point. Just fix it, it will improve your software architecture
- I zoom in on just one function:

```
void addSubunit(int filament, double &lengthTube, std::vector<double> &lengthFilaments)
{
    lengthFilaments[filament] /* */;
    // ...
}
```

Instead of supplying a std::vector (`lengthFilaments`) and an index (`filament`), you can also directly supply only the element (`lengthFilaments[filament]`) as a `double&`. This will make your code shorter, more readable and more general.
- Replace `verify` by a useful idiom (crashing a computer in both debug and release mode is very unhelpful). If it is for debugging, replace it by `assert`, else make it throw an exception

**Comment by richelbilderbeek** [comment]
I give up getting all tools to work in that folder.

**Comment by Lumphie** [comment]
That's fine! I got it too work for the assignment anyway.

Just one quick question 

```
void addSubunit(int filament, double &lengthTube, std::vector<double> &lengthFilaments)
{
    lengthFilaments[filament] /* */;
    // ...
}
```

Instead of supplying a std::vector (lengthFilaments) and an index (filament), you can also directly supply only the element (lengthFilaments[filament]) as a double&. This will make your code shorter, more readable and more general.

Would that work? Since I need to change the value of that member in the std::vector.

**Comment by richelbilderbeek** [comment]
Yes, that would work!

Another idea (that will definitely land you a high grade):
- add a visualisation! `std::cout` stands for asCiiart OUTput :sunglasses:

**Comment by richelbilderbeek** [comment]
Another idea:
- replace the code from Sander by standard C++ classes (you can peek in e.g [ribi_simulation.cpp](https://github.com/richelbilderbeek/pbdmms/blob/master/ribi_simulation.cpp))
